org: vedantkhandelwal # Enter your tenant name here
app: workshop # Enter your application name here
service: fullstack-restapi # update

provider:
  name: aws
  runtime: nodejs10.x
  region: us-east-1
  stage: issue-number
  environment:
    database_submissions_name: ${output::dev::fullstack-database.database_submissions_name}
    database_submissions_region: ${output::dev::fullstack-database.database_submissions_region}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
      Resource: "arn:aws:dynamodb:*:*:table/${output::dev::fullstack-database.database_submissions_name}"

functions:
  formSubmit:
    handler: index.submit
    timeout: 10
    events:
      - http:
          path: submit
          method: post
          cors: true